# Generated by Django 5.0.1 on 2024-01-16 15:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text_color', models.CharField(max_length=7)),
                ('background_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('publish_date', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, validators=[blog.models.validate_email_domain])),
                ('categories', models.ManyToManyField(to='blog.category')),
            ],
        ),
    ]
